async:
    dao:
     mapperLocations: /mapper
     basePackages: com.tg.example.dao
     username: root
     host: 10.100.216.147
     port: 3306
     password: UJ9FeAm3Yc@#E%IH8dLj6guyr5K&u#J3
     database: test
     maxTotal: 12
     maxIdle: 12
     minIdle: 1
     maxWaitMillis: 10000



